name: CI/CD Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: echo ${{ github.ref }}

  release:
    if: github.ref == 'refs/heads/master-test'

    needs: build

    runs-on: ubuntu-latest

    steps:
    - run: echo ${{ github.ref }}
